apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "jwt-fhir"
  namespace: datamesh
spec:
  selector:
    matchLabels:
      app: fhir-server
  jwtRules:
  - issuer: "https://keycloak.idea.lst.tfo.upm.es/realms/IDEA4RC"
    jwksUri: "https://keycloak.idea.lst.tfo.upm.es/realms/IDEA4RC/protocol/openid-connect/certs"