apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: datamesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: harbor2.vantage6.ai/infrastructure/ohdsi-api:latest
        command: ["celery", "-A", "api.celery_app", "worker", "-l", "DEBUG", "-P", "solo"]
        env:
          - name: CELERY_BROKER_URL
            valueFrom:
              configMapKeyRef:
                name: connection-details
                key: CELERY_BROKER_URL
          - name: CELERY_RESULT_BACKEND
            valueFrom:
              configMapKeyRef:
                name: connection-details
                key: CELERY_RESULT_BACKEND
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: connection-details
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: connection-details
                key: POSTGRES_USER
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: connection-details
                key: POSTGRES_DB
          
---
---
apiVersion: v1
kind: Service
metadata:
  name: celery-service
  namespace: datamesh
spec:
  selector:
    app: celery-worker
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
    - protocol: TCP
      port: 15672
      targetPort: 15672