apiVersion: apps/v1
kind: service
metadata:
  name: omop-postgres-service
  namespace: datamesh
spec:
  selector:
    app: omop-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP