apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-db
  namespace: datamesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhir-db
  template:
    metadata:
      labels:
        app: fhir-db
    spec:
      containers:
        - name: fhir-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: idea4rc