apiVersion: v1
kind: ConfigMap
metadata:
  name: connection-details
  namespace: datamesh
data:
  CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq-service.datamesh.svc.cluster.local:5672/"
  CELERY_RESULT_BACKEND: "db+postgresql://ohdsi:ohdsi@celery-db-service.datamesh.svc.cluster.local:5454/ohdsi"
  
  POSTGRES_USER: "ohdsi"
  POSTGRES_PASSWORD: "ohdsi"
  POSTGRES_DB: "ohdsi"
  
  OMOP_DBMS: "postgresql"
  OMOP_SERVER: "omop-postgres-service.datamesh.svc.cluster.local"
  OMOP_PORT: "5432"
  OMOP_USER: "postgres"
  OMOP_PASSWORD: "mysecretpassword"
  OMOP_DATABASE: "omopdb"
  OMOP_CDM_SCHEMA: "omopcdm"