apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: demo-installation
spec:
  profile: demo
  meshConfig:
        accessLogFile: /dev/stdout
        enableTracing: true
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true