apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: datamesh-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:      
      number: 80      
      name: http      
      protocol: HTTP
    # TODO:      
    # hosts:    
    # - idea.domain.eu